# Site settings

exclude: [vendor]

# Title of the site
title: "Every Kid in a Park"
base_url: "http://ekip-staging.18f.gov"

# Basic meta description for pages that don't have one specified
description: "Every Kid in a Park Staging Site"

# Replace with your Google Analytics ID, eg: UA-12345678-9
google_analytics_id: ''

# Show a warning to users of IE 8 and below
show_ie_warning: True

## Social Media Settings
twitter_username: ''
twitter_image: ''

# Build settings
markdown: kramdown
permalink: pretty

source: app/
destination: _deploy/

ticket_generator_endpoint: https://ekip-staging.18f.gov/ticket
